import {BoltIcon} from '../../lib/icons'
import {defineArrayMember, defineField, defineType} from 'sanity'

import {experienceCategories, experienceFormats, experienceSeasons} from '../constants'
import {featuredField, orderRankField, slugField} from '../fields'

export const experience = defineType({
  name: 'experience',
  title: 'Experience',
  type: 'document',
  icon: BoltIcon,
  groups: [
    {name: 'content', title: 'Content', default: true},
    {name: 'visit', title: 'Visit info'},
    {name: 'related', title: 'Related'},
    {name: 'seo', title: 'SEO'},
    {name: 'settings', title: 'Settings'},
  ],
  fields: [
    defineField({
      name: 'title',
      title: 'Title',
      type: 'string',
      group: 'content',
      description: 'Public name of this farm experience.',
      validation: (rule) => rule.required().max(80),
    }),
    slugField('title', 'content'),
    defineField({
      name: 'shortDescription',
      title: 'Short description',
      type: 'text',
      rows: 3,
      group: 'content',
      description: 'Used on the Experiences hub and cards.',
      validation: (rule) => rule.required().max(220),
    }),
    defineField({
      name: 'body',
      title: 'Full description',
      type: 'portableText',
      group: 'content',
      description: 'Main story on the individual experience page.',
    }),
    defineField({
      name: 'heroImage',
      title: 'Hero image',
      type: 'altImage',
      group: 'content',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'gallery',
      title: 'Gallery',
      type: 'array',
      group: 'content',
      of: [defineArrayMember({type: 'altImage'})],
      options: {layout: 'grid'},
    }),
    defineField({
      name: 'category',
      title: 'Experience type',
      type: 'string',
      group: 'visit',
      description: 'Helps group similar experiences on the website.',
      options: {list: [...experienceCategories]},
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'animalSpecies',
      title: 'Animals / species this experience features',
      type: 'array',
      group: 'visit',
      description: 'Optional grouping, for example alpacas or highland cattle. Individual animals are chosen below.',
      of: [defineArrayMember({type: 'reference', to: [{type: 'animalSpecies'}]})],
    }),
    defineField({
      name: 'season',
      title: 'Season',
      type: 'string',
      group: 'visit',
      options: {list: [...experienceSeasons]},
      initialValue: 'yearRound',
    }),
    defineField({
      name: 'duration',
      title: 'Duration',
      type: 'string',
      group: 'visit',
      description: 'Shown on the website, for example “2 hours” or “Overnight”.',
    }),
    defineField({
      name: 'priceDisplay',
      title: 'Price shown on the website',
      type: 'string',
      group: 'visit',
      description: 'Display text only, for example “From $45”. Booking is handled by the booking URL.',
    }),
    defineField({
      name: 'groupSize',
      title: 'Group size',
      type: 'string',
      group: 'visit',
      description: 'Optional, for example “Up to 8 guests”.',
    }),
    defineField({
      name: 'sessionType',
      title: 'Private or shared',
      type: 'string',
      group: 'visit',
      options: {list: [...experienceFormats]},
    }),
    defineField({
      name: 'ageGuidance',
      title: 'Age guidance',
      type: 'string',
      group: 'visit',
    }),
    defineField({
      name: 'visitorInfo',
      title: 'Important visitor information',
      type: 'portableText',
      group: 'visit',
      description: 'What guests need to know before they come.',
    }),
    defineField({
      name: 'accessibilityInfo',
      title: 'Accessibility information',
      type: 'portableText',
      group: 'visit',
    }),
    defineField({
      name: 'bookingUrl',
      title: 'Booking link',
      type: 'url',
      group: 'visit',
      description: 'Where the Book button should send guests.',
      validation: (rule) => rule.uri({scheme: ['http', 'https']}),
    }),
    defineField({
      name: 'animals',
      title: 'Animals guests will meet',
      type: 'array',
      group: 'related',
      description: 'Choose from Meet the Herd. Animal photos and stories stay on the animal record.',
      of: [defineArrayMember({type: 'reference', to: [{type: 'animal'}]})],
    }),
    defineField({
      name: 'faqs',
      title: 'Related FAQs',
      type: 'array',
      group: 'related',
      description: 'These same FAQs can also appear on the site-wide FAQ page.',
      of: [defineArrayMember({type: 'reference', to: [{type: 'faq'}]})],
    }),
    defineField({
      name: 'testimonials',
      title: 'Related testimonials',
      type: 'array',
      group: 'related',
      of: [defineArrayMember({type: 'reference', to: [{type: 'testimonial'}]})],
    }),
    defineField({
      name: 'cancellationPolicy',
      title: 'Cancellation policy',
      type: 'reference',
      group: 'related',
      description: 'Reuse a policy instead of pasting it on every experience.',
      to: [{type: 'policy'}],
    }),
    defineField({
      name: 'welfarePolicy',
      title: 'Animal welfare information',
      type: 'reference',
      group: 'related',
      to: [{type: 'policy'}],
    }),
    defineField({
      name: 'relatedExperiences',
      title: 'Related experiences',
      type: 'array',
      group: 'related',
      of: [defineArrayMember({type: 'reference', to: [{type: 'experience'}]})],
    }),
    defineField({
      name: 'sections',
      title: 'Additional page sections',
      type: 'pageBuilder',
      group: 'content',
      description: 'Optional extra sections below the standard experience layout.',
    }),
    defineField({
      name: 'seo',
      title: 'SEO',
      type: 'seo',
      group: 'seo',
    }),
    defineField({
      name: 'active',
      title: 'Show on the website',
      type: 'boolean',
      group: 'settings',
      description: 'Turn off to hide this experience without deleting it.',
      initialValue: true,
    }),
    featuredField('settings'),
    orderRankField('Lower numbers appear first on the Experiences hub.', 'settings'),
  ],
  preview: {
    select: {
      title: 'title',
      media: 'heroImage',
      active: 'active',
      category: 'category',
    },
    prepare({title, media, active, category}) {
      return {
        title: title || 'Untitled experience',
        subtitle: `${category || 'Experience'}${active === false ? ' · hidden' : ''}`,
        media,
      }
    },
  },
})
